### ISSUE TITLE
Post Voting view rendered incorrectly

### ISSUE THREAD

**Issue by AksharPrasanna** [samuelezedi/polls#1]
I tried running the code given in the example. I noticed that the value of for an option, even though updated is not rendered in the post voting view for some reason.
So, our vote is not taken into account. 

For instance, in the attached screenshot, I have voted for Mecca which is still at 0.
The values set for options prior to voting is taken and not updated after voting.

![WhatsApp Image 2020-07-11 at 12 06 29 AM](https://user-images.githubusercontent.com/33616248/87187271-8663d400-c30a-11ea-91eb-22bb19248a7c.jpeg)

**Comment by samuelezedi** [comment]
Okay noted, I will check this out and update you ASAP, but my guess is the example app might be running on an older version, but let me check it out ASAP

**Comment by samuelezedi** [comment]
Okay, so the reason you have this error is that you are using an older version. I think you are using version 0.1.4, update to 0.1.8

**Comment by AksharPrasanna** [comment]
Thanks for the quick response!

I have been using 0.1.8 itself - polls: ^0.1.8

Am I missing something here ? Something else that I need to take care ?

**Comment by samuelezedi** [comment]
Thanks for the correction, I am also updating the package today to 0.2.1 it will go along with your fix and a few other fixes

PollsOptions class will be deprecated, viewType will be deprecated also

you will now have voteData which will take a map of voters and their choice. In the long run, the new release is simple trying to remove a lot of the logic from the user side, So you won't have to do some many things

**Comment by samuelezedi** [comment]
Issue has been resolved in AksharPrasanna's pull request
