### ISSUE TITLE
Not showing options more then 4.

### ISSUE THREAD

**Issue by OsamaQureshi796** [samuelezedi/polls#4]
i have created a poll but it only show 4 options but i have to show 6 options in poll widget.

**Comment by samuelezedi** [comment]
currently working on making this more flexible, at this time, it only allows 4 options. hopefully before the end of the weekend a   new version will be out to support as many options

**Comment by OsamaQureshi796** [comment]
Ok Thanks.
But for now i have added library and added necessary code for 10 poll options.
